export default class Constants {
  static ALL_ELEMENTS = [
    'Archetype',
    'Archetype Feature',
    'Grants',
    'Magic Item',
    'Option',
    'Item',
    'Weapon',
    'Proficiency',
    'Weapon Property',
    'Support',
    'Rule',
    'Ability Score Improvement',
    'Race',
    'Racial Trait',
    'Class Feature',
    'Source',
    'Sub Race',
    'Information',
    'Vision',
    'Companion',
    'Companion Trait',
    'Companion Action',
    'Language',
    'Background',
    'Background Feature',
    'Background Variant',
    'Class',
    'Deity',
    'Feat',
    'Feat Feature',
    'Armor',
    'Race Variant',
    'Spell'
  ]

  static ELEMENTS_PLURAL = {
    archetype: 'Archetypes',
    archetypefeature: 'Archetype Features',
    grant: 'Grants',
    magicitem: 'Magic Items',
    option: 'Options',
    item: 'Items',
    weapon: 'Weapons',
    proficiency: 'Proficiencies',
    weaponproperty: 'Weapon Properties',
    support: 'Supports',
    rule: 'Rules',
    abilityscoreimprovement: 'Ability Score Improvements',
    race: 'Races',
    racialtrait: 'Racial Traits',
    classfeature: 'Class Features',
    source: 'Sources',
    subrace: 'Sub Races',
    information: 'Informations',
    vision: 'Visions',
    companion: 'Companions',
    companiontrait: 'Companion Traits',
    companionaction: 'Companion Actions',
    language: 'Languages',
    background: 'Backgrounds',
    backgroundfeature: 'Background Features',
    backgroundvariant: 'Background Variants',
    class: 'Classes',
    deity: 'Deities',
    feat: 'Feats',
    featfeature: 'Feat Features',
    armor: 'Armors',
    racevariant: 'Race Variants',
    spell: 'Spells'
  }
}
